import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "next-themes";
import { StoreProvider, useStore } from "@/app/store";

import ModalProvider from "@/components/modals/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Acans Next App",
  description: "Generated by Acans",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout start");
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StoreProvider>
          <SessionProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <ModalProvider>{children}</ModalProvider>
              <Toaster />
            </ThemeProvider>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
